travis:
  secure:
    BINSTAR_TOKEN: i1sIryA7icfnmi6AsHiKmSuB4h5zxEWMKVO6v6UIw1tZlmGmBHZsXqtnpPbe+Yr0lxzWFZ6Sd+JbMkM5FSXBUXt6zc6uc3GPvcryDvsge7XTHL6NmxmNn6PExG91Ko5BOhjttrPj7yKkIfTzmhMJo4h26uEfFe70H6nlHtZ3gr7CRlYG0pO03iT7+cx+p0IDOQiuVZtAJTUTIcbUHqc5SgjSxyNk9HOHueWfWtNGgPSn59rXq0ZtwdXOGx9SDP1XiHF0ikCdwILrNH6EMXKZwendiGRbrgVPkjv/YycQK5WNvRGos51XbRRhploGBO11LyE/IIdVEvUoZkwJ9tQKAZDLNUzK27IoOnUe4wOsKXRgX4ln9urf9nO8JnJ9y60NUARoqKZ9VtOT4tBVOWPbQnT+Yqdia+tYQlWcIoPX622NpZ0Yt81ZcY6o7iXPf36nTbfiCyHrrA3xWPj7qJzfDOjwguju41UdAmhTixIQh+VxSRnBLeVUxCrITHgOgHduf6DrvsGzLtPGkkt68UvizNi0s+phcdpdqkrG/MqLMIm0bgpXThxWFqDgwPRMFEt47tl/Q0v0cJ6TaJhzamZUsbiSlTQbcZsLo9+xwBgI+f5oi49V7I9kwGCrEelV2BT8CDAwNodNSqDrCp/6MJAFHr/smlJx15Vo0Wer/6Fu7z8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
