travis:
  secure:
    BINSTAR_TOKEN: Gq5IAAjS/uCz5P0gwCfitBeTMHwR7DEbeh6oc2LZDIhrcbV1xFiKSVleTaaBT2pdxdywoonQsoNDiuEuDsWR7LGUjLxJLaIW9YQNZXOQlGC7L24vvkXpXgzxX1AtiF3T6+2L1jziJ6ocAiI5myVLGk9KNEPcYZb1Ks+MZyyFe/rTYA1McgUO0XR6HG4Y+jBcGY15OP8Q/HKa4h6+doXpueDgYd5+rpIyd/6FnRNPlf+qqwA4m5unmuntsZc3+suuBNnqkuS7KgIqDd7GS8oUamq+rf1l4OUqaS1wtleN8Wue9sApFy/2uiER3VHyGk38Qz6MQqmzgARBIDAUmMC1Qe6xqAlITqe0K9WToSnluyT2UzeSZAom1rgJ4A6pqIbpiQ3+eZfDU9aEs7qJ2BYlg3H3RHXPX11DJQphMqCLPUeYT+u/2WDjD26x8j7MOVXZGZ9oy4PzscALC6qEoxZHn08935EwtFTqW31kVf0RiPm2nmGCrFeZtirTOwFfVm7tJw2gZ4Tb3fC1YC4wpG6Qjng8ZwOQd+igjoDjcbR9PnR1E5jzzgHga0/SRmq42a9ktszUCtPKSI4ZeIOYPFywVu+idBfjW6gP6lvmwpxgwjU9LV1S6Rxdg2KgBynq1s52BOzq+CZXqkEwCqME+RAjt+Y1Xaw87bfqhrdGZWSs8j4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
